[WIP] Dapr docs for .NET SDK
dapr-sandbox/components-dotnet-sdk pull request #5
Opened 2023-01-25 20:48 UTC by philliphoff

A draft of the Dapr docs for the .NET SDK.

2023-01-26 22:27 UTC, philliphoff commented
@hhunter-ms @greenie-msft This is a draft of docs for the new Dapr Pluggable Components .NET SDK. If you have any feedback on structure, please let me know.

2023-02-09 20:53 UTC, philliphoff commented
@hhunter-ms @greenie-msft I think I've got the pretty good start on these docs; if you have a chance to look them over I'd appreciate it.

2023-02-10 23:12 UTC, hhunter-ms requested changes
quick consistency/grammar pass

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +Creating a Dapr Pluggable Component application is similar to creating an ASP.NET application.  In, `Program.cs`, replace the `WebApplication` related code with the Dapr `DaprPluggableComponentsAppli
```suggestion
Creating a Dapr pluggable component application is similar to creating an ASP.NET application.  In `Program.cs`, replace the `WebApplication` related code with the Dapr `DaprPluggableComponentsApplication` equivalent.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +This creates an application with a single service--each service corresponds to a single Unix Domain Socket, and can host one or more component types.
```suggestion
This creates an application with a single service. Each service:

- Corresponds to a single Unix Domain Socket
- Can host one or more component types
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +Note that only a single component of each type can be registered with an individual service. However, [multiple components of the same type can be spread across multiple services]({{< ref dotnet-mult
```suggestion
Only a single component of each type can be registered with an individual service. However, [multiple components of the same type can be spread across multiple services]({{< ref dotnet-multiple-services >}}).
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +## Testing Components Locally
```suggestion
## Test components locally
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +## Project Creation
```suggestion
## Project creation
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +## Add NuGet Packages
```suggestion
## Add NuGet packages
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +## Create Application and Service
```suggestion
## Create application and service
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +## Implement and Register Components
```suggestion
## Implement and register components
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +Dapr Pluggable Components can be tested by starting the application on the command line and configuring a Dapr sidecar to use it.
```suggestion
Pluggable components can be tested by starting the application on the command line and configuring a Dapr sidecar to use it.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +Add the Dapr .NET Pluggable Components NuGet package.
```suggestion
Add the Dapr .NET pluggable components NuGet package.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +Creating a Dapr Pluggable Component starts with an empty ASP.NET project.
```suggestion
Creating a pluggable component starts with an empty ASP.NET project.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +Development of Dapr Pluggable Components on Windows requires WSL as some development platforms do not fully support Unix Domain Sockets on "native" Windows.
```suggestion
Development of Dapr pluggable components on Windows requires WSL as some development platforms do not fully support Unix Domain Sockets on "native" Windows.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +title: "Getting started with the Dapr Pluggable Components .NET SDK"
```suggestion
title: "Getting started with the Dapr pluggable components .NET SDK"
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +description: How to get up and running with the Dapr Pluggable Components .NET SDK
```suggestion
description: How to get up and running with the Dapr pluggable components .NET SDK
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +Dapr offers NuGet packages to help with the development of .NET Pluggable Components.
```suggestion
Dapr offers NuGet packages to help with the development of .NET pluggable components.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +To configure Dapr to use the component, in the components path directory:
```suggestion
To configure Dapr to use the component, in the resources path directory:
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +dapr run --app-id <app id> --components-path <components path> ...
```suggestion
dapr run --app-id <app id> --resources-path <resources path> ...
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +At this point, the Dapr sidecar will have started and connected via Unix Domain Socket to the component. You can then interact with the component either through the service using the component (if st
```suggestion
At this point, the Dapr sidecar will have started and connected via Unix Domain Socket to the component. You can then interact with the component either:
- Through the service using the component (if started), or 
- By using the Dapr HTTP or gRPC API directly
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +The [.NET 7 and later SDKs](https://dotnet.microsoft.com/en-us/download/dotnet) enable you to create a .NET-based container for your application *without* a `Dockerfile`, even for those targeting ear
```suggestion
The [.NET 7 and later SDKs](https://dotnet.microsoft.com/en-us/download/dotnet) enable you to create a .NET-based container for your application *without* a `Dockerfile`, even for those targeting earlier versions of the .NET SDK. This is probably the simplest way of generating a container for your component today.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +Currently, the .NET 7 SDK requires Docker Desktop on the local machine as well as addition of a special NuGet package, as well as Docker Desktop on the local machine to build containers. Future versi
```suggestion
Currently, the .NET 7 SDK requires Docker Desktop on the local machine, a special NuGet package, and Docker Desktop on the local machine to build containers. Future versions of .NET SDK plan to eliminate those requirements.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +Ensure the architecture argument `--arch x64` matches that of the component's ultimate deployment target. By default, the architecture of the generated container matches that of the local machine. Fo
```suggestion
Ensure the architecture argument `--arch x64` matches that of the component's ultimate deployment target. By default, the architecture of the generated container matches that of the local machine. For example, if the local machine is ARM64-based (for example, a M1 or M2 Mac) and the argument is omitted, an ARM64 container will be generated which may not be compatible with deployment targets expecting an AMD64 container.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +Paths for `COPY` operations in the `Dockerfile` are relative to the Docker context passed when building the image, while the Docker context itself will vary depending on the needs of the project bein
```suggestion
Paths for `COPY` operations in the `Dockerfile` are relative to the Docker context passed when building the image, while the Docker context itself will vary depending on the needs of the project being built (for example, if it has referenced projects). In the example above, the assumption is that the Docker context is the component project directory.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +{{% /alert %}}
```suggestion
{{% /alert %}}


## Next steps
- [Advanced uses of the pluggable components .NET SDK]({{< ref dotnet-advanced >}})
- Implementing:
   - [State store components]({{< ref dotnet-state-store >}})
   - [Bindings components]({{< ref dotnet-bindings >}})
   - [Pub/sub components]({{< ref dotnet-pub-sub >}})
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/_index.md
> +title: "Advanced uses of the Dapr Pluggable Components .NET SDK"
```suggestion
title: "Advanced uses of the Dapr pluggable components .NET SDK"
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/_index.md
> +description: How to use advanced techniques with with the Dapr Pluggable Components .NET SDK
```suggestion
description: How to use advanced techniques with with the Dapr pluggable components .NET SDK
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/_index.md
> +While not typically needed by most, these guides show advanced ways to can configure your .NET Pluggable Components.
```suggestion
While not typically needed by most, these guides show advanced ways to can configure your .NET pluggable components.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-application-environment.md
> +title: "Application Environment of a .NET Dapr Pluggable Component"
```suggestion
title: "Application Environment of a .NET Dapr pluggable component"
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-application-environment.md
> +description: How to configure the environment of a .NET Pluggable Component
```suggestion
description: How to configure the environment of a .NET pluggable component
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-application-environment.md
> +A .NET Dapr Pluggable Component application can be configured, i.e. for dependency injection, logging, and configuration values, in a manner similar to ASP.NET applications.  The `DaprPluggableCompon
```suggestion
A .NET Dapr pluggable component application can be configured for dependency injection, logging, and configuration values similarly to ASP.NET applications.  The `DaprPluggableComponentsApplication` exposes a similar set of configuration properties to that exposed by `WebApplicationBuilder`.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-application-environment.md
> +Components registered with services can participate in dependency injection; arguments in the components constructor will be injected during creation, assuming those types themselves have been regist
```suggestion
Components registered with services can participate in dependency injection. Arguments in the components constructor will be injected during creation, assuming those types have been registered with the application. You can register them through the `IServiceCollection` exposed by `DaprPluggableComponentsApplication`.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-application-environment.md
> +Use of `IServiceCollection.AddScoped()` is not recommended as such instances' lifetimes are bound to a single gRPC method call which does not match the lifetime of an individual component instance.
```suggestion
Use of `IServiceCollection.AddScoped()` is not recommended. Such instances' lifetimes are bound to a single gRPC method call, which does not match the lifetime of an individual component instance.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-application-environment.md
> +.NET Dapr Pluggable Components can use the [standard .NET logging mechanisms](https://learn.microsoft.com/en-us/dotnet/core/extensions/logging). The `DaprPluggableComponentsApplication` exposes an `I
```suggestion
.NET Dapr pluggable components can use the [standard .NET logging mechanisms](https://learn.microsoft.com/en-us/dotnet/core/extensions/logging). The `DaprPluggableComponentsApplication` exposes an `ILoggingBuilder`, through which it can be configured.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-application-environment.md
> +Like with ASP.NET, logger services (e.g. `ILogger<T>`) are pre-registered.
```suggestion
Like with ASP.NET, logger services (for example, `ILogger<T>`) are pre-registered.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-application-environment.md
> +## Dependency Injection
```suggestion
## Dependency injection
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-application-environment.md
> +As .NET Dapr Pluggable Components are built on ASP.NET, they can use its [standard configuration mechanisms](https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration) and default to the
```suggestion
Since .NET pluggable components are built on ASP.NET, they can use its [standard configuration mechanisms](https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration) and default to the same set of [pre-registered providers](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0#default-application-configuration-sources). The `DaprPluggableComponentsApplication` exposes an `IConfigurationManager` through which it can be configured.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-application-environment.md
> +```
Add this at the bottom of the page

```
## Next steps

{{< button text="Pluggable component lifetimes >>" page="dotnet-component-lifetime.md" >}}
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-component-lifetime.md
> +title: "Lifetimes of .NET Dapr Pluggable Components"
```suggestion
title: "Lifetimes of .NET Dapr pluggable components"
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-component-lifetime.md
> +linkTitle: "Component Lifetime"
```suggestion
linkTitle: "Component lifetime"
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-component-lifetime.md
> +description: How to control the lifetime of a .NET Pluggable Component
```suggestion
description: How to control the lifetime of a .NET pluggable component
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-component-lifetime.md
> +There are two ways to register a components:
```suggestion
There are two ways to register a component:
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-component-lifetime.md
> + - A component's lifetime is determined by the Pluggable Component and can be multi-instance or a singleton, as needed
```suggestion
 - A component's lifetime is determined by the pluggable component and can be multi-instance or a singleton, as needed
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-component-lifetime.md
> +## Singleton Components
```suggestion
## Singleton components
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-component-lifetime.md
> +Components registered by type are singletons; one instance will serve all configured Dapr components of that type associated with that socket. This approach is best when only a single component of th
```suggestion
Components registered _by type_ are singletons: one instance will serve all configured components of that type associated with that socket. This approach is best when only a single component of that type exists and is shared amongst Dapr applications.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-component-lifetime.md
> +## Multi-instance Components
```suggestion
## Multi-instance components
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-component-lifetime.md
> +Components can be registered using by passing a "factory method"; this method will be called for each configured Dapr component of that type associated with that socket. The method returns the instan
```suggestion
Components can be registered by passing a "factory method". This method will be called for each configured component of that type associated with that socket. The method returns the instance to associate with that component (whether shared or not). This approach is best when multiple components of the same type may be configured with different sets of metadata, when component operations need to be isolated from one another, etc.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-multiple-services.md
> +A Dapr Pluggable Component can host multiple components of varying types. This might be done for efficiency reasons, to minimize the number of sidecars running in a cluster. It might also be done for
```suggestion
A pluggable component can host multiple components of varying types. You might do this:
- To minimize the number of sidecars running in a cluster
- To group related components that are likely to share libraries and implementation, such as:
   - A database exposed both as a general state store, and
   - Output bindings that allow more specific operations.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-multiple-services.md
> +Each Unix Domain Socket can manage calls to, at most, one component of each type. To host multiple components of the *same* type, those types can be spread across multiple sockets. The SDK binds each
```suggestion
Each Unix Domain Socket can manage calls to one component of each type. To host multiple components of the _same_ type, you can spread those types across multiple sockets. The SDK binds each socket to a "service", with each service composed of one or more component types.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-multiple-services.md
> +## Registering Multiple Services
```suggestion
## Registering multiple services
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-multiple-services.md
> +Each call to `RegisterService()` binds a socket to a set of registered components, where, at most, one of each type of component can be registered per service.
```suggestion
Each call to `RegisterService()` binds a socket to a set of registered components, where one of each type of component can be registered per service.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-multiple-services.md
> +Configuring Dapr to use the hosted components is the same as for any single component; the component YAML just refers to the associated socket.
```suggestion
Configuring Dapr to use the hosted components is the same as for any single component - the component YAML refers to the associated socket.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-component-lifetime.md
> +
Add at bottom of page:

```
## Next steps

{{< button text="Multiple services in a pluggable component >>" page="dotnet-multiple-services.md" >}}
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-multiple-services.md
> +title: "Multiple services in a .NET Dapr Pluggable Component"
```suggestion
title: "Multiple services in a .NET Dapr pluggable component"
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-multiple-services.md
> +description: How to expose multiple services from a .NET Pluggable Component
```suggestion
description: How to expose multiple services from a .NET pluggable component
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-advanced/dotnet-multiple-services.md
> +```
Add to bottom of page:

````
## Next steps
Learn how to implement one of the following components with the pluggable component SDK:
- [Input/output bindings]({{< ref dotnet-bindings >}})
- [Pub/sub]({{< ref dotnet-pub-sub >}})
- [State store]({{< ref dotnet-state-store >}})

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-bindings/_index.md
> +description: How to create an input/output binding with the Dapr Pluggable Components .NET SDK
```suggestion
description: How to create an input/output binding with the Dapr pluggable components .NET SDK
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-bindings/_index.md
> +## Add Bindings Namespaces
```suggestion
## Add bindings namespaces
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-bindings/_index.md
> +## Input Bindings: Implement `IInputBinding`
```suggestion
## Input bindings: Implement `IInputBinding`
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-bindings/_index.md
> +Calls to the `ReadAsync()` method are "long-lived" in that the method is not expected to return until canceled (i.e. via the `cancellationToken`). As messages are read from the underlying store of th
```suggestion
Calls to the `ReadAsync()` method are "long-lived", in that the method is not expected to return until canceled (for example, via the `cancellationToken`). As messages are read from the underlying store of the component, they are delivered to the Dapr runtime via the `deliveryHandler` callback. Delivery allows the component to receive notification if/when the application (served by the Dapr runtime) acknowledges processing of the message.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-bindings/_index.md
> +## Output Bindings: Implement `IOutputBinding`
```suggestion
## Output bindings: Implement `IOutputBinding`
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-bindings/_index.md
> +## Input *and* Output Binding Components
```suggestion
## Input and output binding components
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-bindings/_index.md
> +A component can be *both* an input *and* output binding, simply by implementing both interfaces.
```suggestion
A component can be _both_ an input _and_ output binding, simply by implementing both interfaces.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-bindings/_index.md
> +## Register Binding Component
```suggestion
## Register binding component
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-bindings/_index.md
> +In the main program file (e.g. `Program.cs`), register the binding component in an application service.
```suggestion
In the main program file (for example, `Program.cs`), register the binding component in an application service.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-bindings/_index.md
> +{{% /alert %}}
Add this at the bottom of the page:

```
## Next steps
Learn how to implement a different component with the pluggable component SDK:
   - [Pub/sub]({{< ref dotnet-pub-sub >}})
   - [State store]({{< ref dotnet-state-store >}})
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-pub-sub/_index.md
> +title: "Implementing a .NET pub-sub component"
```suggestion
title: "Implementing a .NET pub/sub component"
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-pub-sub/_index.md
> +linkTitle: "Pub-Sub"
```suggestion
linkTitle: "Pub/sub"
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-pub-sub/_index.md
> +description: How to create a pub-sub with the Dapr Pluggable Components .NET SDK
```suggestion
description: How to create a pub/sub with the Dapr pluggable components .NET SDK
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-pub-sub/_index.md
> +Creating a pub-sub component requires just a few basic steps.
```suggestion
Creating a pub/sub component requires just a few basic steps.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-pub-sub/_index.md
> +## Add Pub-Sub Namespaces
```suggestion
## Add pub/sub namespaces
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-pub-sub/_index.md
> +Add `using` statements for the pub-sub related namespaces.
```suggestion
Add `using` statements for the pub/sub related namespaces.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-pub-sub/_index.md
> +Calls to the `PullMessagesAsync()` method are "long-lived" in that the method is not expected to return until canceled (i.e. via the `cancellationToken`). The "topic" from which messages should be pu
```suggestion
Calls to the `PullMessagesAsync()` method are "long-lived", in that the method is not expected to return until canceled (for example, via the `cancellationToken`). The "topic" from which messages should be pulled is passed via the `topic` argument, while the delivery to the Dapr runtime is performed via the `deliveryHandler` callback. Delivery allows the component to receive notification if/when the application (served by the Dapr runtime) acknowledges processing of the  message.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-pub-sub/_index.md
> +## Register Pub-Sub Component
```suggestion
## Register pub/sub component
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-pub-sub/_index.md
> +In the main program file (e.g. `Program.cs`), register the pub-sub component with an application service.
```suggestion
In the main program file (for example, `Program.cs`), register the pub/sub component with an application service.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-pub-sub/_index.md
> +```
Add to bottom of page:

```
## Next steps
Learn how to implement a different component with the pluggable component SDK:
   - [Input/output bindings]({{< ref dotnet-bindings >}})
   - [State store]({{< ref dotnet-state-store >}})
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-state-store/_index.md
> +| `BulkDeleteRowMismatchException` | Bulk Delete | When the number of affected rows does not match the expected rows |
Add to bottom of page:

```
[Learn more about returning semantic errors with examples](https://v1-10.docs.dapr.io/developing-applications/develop-components/pluggable-components/develop-pluggable/#returning-semantic-errors)

## Next steps
Learn how to implement a different component with the pluggable component SDK:
   - [Input/output bindings]({{< ref dotnet-bindings >}})
   - [Pub/sub]({{< ref dotnet-pub-sub >}})
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-state-store/_index.md
> +description: How to create a state store with the Dapr Pluggable Components .NET SDK
```suggestion
description: How to create a state store with the Dapr pluggable components .NET SDK
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-state-store/_index.md
> +## Add State Store Namespaces
```suggestion
## Add state store namespaces
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-state-store/_index.md
> +## Register State Store Component
```suggestion
## Register state store component
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-state-store/_index.md
> +In the main program file (e.g. `Program.cs`), register the state store with an application service.
```suggestion
In the main program file (for example, `Program.cs`), register the state store with an application service.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-state-store/_index.md
> +## Bulk State Stores
```suggestion
## Bulk state stores
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-state-store/_index.md
> +The Dapr runtime will emulate bulk state store operations for state stores that do *not* implement `IBulkStateStore` by calling its operations individually.
```suggestion
The Dapr runtime will emulate bulk state store operations for state stores that do _not_ implement `IBulkStateStore` by calling its operations individually.
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-state-store/_index.md
> +## Transactional State Stores
```suggestion
## Transactional state stores
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-state-store/_index.md
> +## Queryable State Stores
```suggestion
## Queryable state stores
```

2023-02-10 23:12 UTC, hhunter-ms commented on daprdocs/content/en/dotnet-sdk-docs/dotnet-state-store/_index.md
> +## ETag and Other Semantic Error Handling
```suggestion
## ETag and other semantic error handling
```

2023-02-10 23:12 UTC, hhunter-ms commented
@philliphoff sorry for the delay - did a quick consistency/grammar pass. thanks for these docs!

2023-02-11 00:05 UTC, philliphoff commented on daprdocs/content/en/dotnet-sdk-docs/_index.md
> +To configure Dapr to use the component, in the components path directory:
Good catch!

2023-02-13 17:10 UTC, hhunter-ms approved these changes

2023-02-13 17:13 UTC, merged